### ISSUE TITLE
 xpsnr：The results of calculating xpsnr twice are different

### ISSUE THREAD

**Issue by rtingo** [fraunhoferhhi/xpsnr#2] opened 2021-07-22 10:50 UTC
It comes a problem when calculating xpsnr. 
Use the same command to calculate the same data  twice, and the two results are different(Y component is the same, but U V not). The following is the result：
once
16.log:[Parsed_xpsnr_0 @ 0x7ffce1604140] XPSNR  Y: 25.9095  U: 12.6721  V: 9.9461
32.log:[Parsed_xpsnr_0 @ 0x7fbdb2414b40] XPSNR  Y: 28.1861  U: 12.6572  V: 9.9295
64.log:[Parsed_xpsnr_0 @ 0x7fb068f10ec0] XPSNR  Y: 30.3669  U: 13.8425  V: 10.2582
128.log:[Parsed_xpsnr_0 @ 0x7fa936404080] XPSNR  Y: 32.3954  U: 13.9056  V: 10.2615
twice
16.log:[Parsed_xpsnr_0 @ 0x7fe7f4f04080] XPSNR  Y: 25.9095  U: 12.9179  V: 10.0258
32.log:[Parsed_xpsnr_0 @ 0x7ff017e0a380] XPSNR  Y: 28.1861  U: 14.0122  V: 10.3102
64.log:[Parsed_xpsnr_0 @ 0x7ff9f4f04080] XPSNR  Y: 30.3669  U: 13.5671  V: 10.1994
128.log:[Parsed_xpsnr_0 @ 0x7fc5b4c0e380] XPSNR  Y: 32.3954  U: 14.5441  V: 10.4173

(Mac Intel Core i7) and command：
./ffmpeg -s 720x1280 -framerate 20 -f rawvideo -pix_fmt yuv420p10le -i 10bit.yuv -s 720x1280 -framerate 20 -f rawvideo -pix_fmt yuv420p10le -i b10.yuv -threads 1 -vframes 15  -lavfi xpsnr="stats_file=xpsnr.log" 

and, There is no problem when calculating psnr.

**Comment by crhelmrich** [comment] 2021-07-26 10:37
Hi, thanks for this report! Unfortunately, I work primarily on Windows and cannot reproduce this issue there. What strikes me is that your U and V values are, in general, very low compared to the Y results. Is that related to the input YUVs that you're using, or do they contain typical color video?

And how did you compile XPSNR into FFmpeg? Using command `./configure --extra-cflags=-mavx2` or a configuration without the AVX2?

By the way, under Windows I had to add `-f null -` to the command-line, otherwise it would complain about an "unconnected output". Is that unnecessary under Mac?

Christian

**Comment by rtingo** [comment] 2021-08-02 02:20
> Hi, thanks for this report! Unfortunately, I work primarily on Windows and cannot reproduce this issue there. What strikes me is that your U and V values are, in general, very low compared to the Y results. Is that related to the input YUVs that you're using, or do they contain typical color video?
> 
> And how did you compile XPSNR into FFmpeg? Using command `./configure --extra-cflags=-mavx2` or a configuration without the AVX2?
> 
> By the way, under Windows I had to add `-f null -` to the command-line, otherwise it would complain about an "unconnected output". Is that unnecessary under Mac?
> 
> Christian

Hi, thanks for your answer！It is, Compared to Y values(xpsnr results), U and V values are very low. The more important problem is that the same command and video will have different U and V results between the two runs(Y results is same in 10bit video). but, its psnr results are normal（as follow）, I think it is a typical color video.

16.log:[Parsed_psnr_0 @ 0x7fd200f04080] PSNR y:28.456892 u:39.824888 v:37.276978 average:30.001574 min:29.358983 max:32.981033
32.log:[Parsed_psnr_0 @ 0x7fbb1a20a500] PSNR y:30.291004 u:40.642944 v:38.367455 average:31.790733 min:31.288218 max:35.018897
64.log:[Parsed_psnr_0 @ 0x7fc57e010f80] PSNR y:32.798802 u:41.575378 v:39.767701 average:34.211927 min:33.688120 max:36.854537
128.log:[Parsed_psnr_0 @ 0x7f9a10f09e40] PSNR y:34.892910 u:42.614993 v:41.177989 average:36.235759 min:35.447414 max:39.056669

 I use the command ./configure --extra-cflags=-mavx2；I had to add [-f null -], but it Is unnecessary under Mac if the command-line contains [-lavfi xpsnr="stats_file=xpsnr.log" -y out.yuv]

**Comment by rtingo** [comment] 2021-08-02 04:40
> Hi, thanks for this report! Unfortunately, I work primarily on Windows and cannot reproduce this issue there. What strikes me is that your U and V values are, in general, very low compared to the Y results. Is that related to the input YUVs that you're using, or do they contain typical color video?
> 
> And how did you compile XPSNR into FFmpeg? Using command `./configure --extra-cflags=-mavx2` or a configuration without the AVX2?
> 
> By the way, under Windows I had to add `-f null -` to the command-line, otherwise it would complain about an "unconnected output". Is that unnecessary under Mac?
> 
> Christian

and the following is the 8bit video used. I use the command ( ffmpeg  -i {$br}0000_qpa_0.mp4 -vframes 15 -pix_fmt yuv420p mp4toyuv.yuv) to get yuv.
Original video：
https://user-images.githubusercontent.com/34804495/127804483-dc227bfb-3afe-4715-b482-66dd92882869.mp4
test-bitrate-160k：
https://user-images.githubusercontent.com/34804495/127804525-65c8bef3-fae8-4913-a2e0-16e0edc24fe4.mp4
test-bitrate-320k：
https://user-images.githubusercontent.com/34804495/127804568-8ea492c1-1145-4d77-b9c5-3f4785f628e9.mp4
test-bitrate-640k：
https://user-images.githubusercontent.com/34804495/127804588-14fe9d8c-8546-4a75-b38b-f89d8712b115.mp4
test-bitrate-1280k(best quality)：
https://user-images.githubusercontent.com/34804495/127804616-b8368637-281f-4356-93aa-72e847d54641.mp4

1.psnr
using the command : ffmpeg -s 720x1280 -framerate 20 -f rawvideo -pix_fmt yuv420p -i 8bit_f15.yuv -s 720x1280 -framerate 20 -f rawvideo -pix_fmt yuv420p -i {$br}0000_qpa_0.yuv -threads 1 -vframes 15  -lavfi psnr="stats_file=psnr.log"  -f null - 2>$br.log

and  the results is is normal.

16.log:[Parsed_psnr_0 @ 0x7f8906804080] PSNR y:28.423931 u:39.698942 v:37.195720 average:29.965467 min:29.324246 max:32.934787
32.log:[Parsed_psnr_0 @ 0x7ffb24104580] PSNR y:30.254209 u:40.496030 v:38.270439 average:31.749297 min:31.248134 max:34.960314
64.log:[Parsed_psnr_0 @ 0x7fa3bf704180] PSNR y:32.753475 u:41.400148 v:39.645485 average:34.158977 min:33.637968 max:36.780212
128.log:[Parsed_psnr_0 @ 0x7fda90d04c80] PSNR y:34.835169 u:42.400344 v:41.015107 average:36.166221 min:35.385164 max:38.948559

2.xpsnr
using the command : ffmpeg -s 720x1280 -framerate 20 -f rawvideo -pix_fmt yuv420p -i 8bit_f15.yuv -s 720x1280 -framerate 20 -f rawvideo -pix_fmt yuv420p -i {$br}0000_qpa_0.yuv -threads 1 -vframes 15  -lavfi xpsnr="stats_file=xpsnr.log"  -f null - 2>$br.log

and  the results is weird, because the 128.log(test-bitrate-1280k) has the best psnr quality.

16.log:[Parsed_xpsnr_0 @ 0x7ff9cb604240] XPSNR  Y: 17.0891  U: 18.7729  V: 18.0549  (minimum: 17.0891)
32.log:[Parsed_xpsnr_0 @ 0x7fe616f04080] XPSNR  Y: 17.0349  U: 18.7816  V: 18.0469  (minimum: 17.0349)
64.log:[Parsed_xpsnr_0 @ 0x7f85e4e0b0c0] XPSNR  Y: 16.9939  U: 18.7777  V: 18.0384  (minimum: 16.9939)
128.log:[Parsed_xpsnr_0 @ 0x7fb8ca804080] XPSNR  Y: 16.9757  U: 18.7756  V: 18.0353  (minimum: 16.9757)

**Comment by crhelmrich** [comment] 2021-08-04 19:05
Thanks for the demo YUV files and the detailed description! I've confirmed your results on my side, and we will look into this issue. In the meantime: do you still observe this problem with "landscape" video resolutions of, e.g., 1280x720 instead of 720x1080?

Christian

**Comment by rtingo** [comment] 2021-08-05 05:19
> Thanks for the demo YUV files and the detailed description! I've confirmed your results on my side, and we will look into this issue. In the meantime: do you still observe this problem with "landscape" video resolutions of, e.g., 1280x720 instead of 720x1280?
> 
> Christian

Hi, thanks for your answer！I have rotated the video, and tried to calculate the video with resolutions 1280x720, its results is normal （as follow）, So this problem only appears on videos that are taller than wide（hight>width)?

16.log:[Parsed_xpsnr_0 @ 0x7fcc80504140] XPSNR  Y: 25.8421  U: 34.9869  V: 32.5333  (minimum: 25.8421)
32.log:[Parsed_xpsnr_0 @ 0x7fac99705a00] XPSNR  Y: 27.5404  U: 35.9073  V: 33.7450  (minimum: 27.5404)
64.log:[Parsed_xpsnr_0 @ 0x7fbbf6604080] XPSNR  Y: 29.8010  U: 36.8520  V: 35.1790  (minimum: 29.8010)
128.log:[Parsed_xpsnr_0 @ 0x7fbbf6605700] XPSNR  Y: 31.7029  U: 37.6421  V: 36.4987  (minimum: 31.7029)

**Comment by crhelmrich** [comment] 2021-08-06 18:52
OK, we found the issue, at least for 8-bit 720p input. Please update to the newest revision 338138a1, rebuild on top of FFmpeg 4.4 (https://github.com/FFmpeg/FFmpeg/releases/tag/n4.4), and let me know if the issue is fixed on your side at least for your 8-bit experiment which you mentioned 5 days ago.

Christian

**Comment by rtingo** [comment] 2021-08-10 09:14
> OK, we found the issue. Please update to the newest revision [1a532af](https://github.com/fraunhoferhhi/xpsnr/commit/1a532af399cd8e491c5c743422797338b5e2ce99), rebuild on top of FFmpeg 4.4 (https://github.com/FFmpeg/FFmpeg/releases/tag/n4.4), and let me know if the issue is fixed on your side. If you want to stick with FFmpeg version 4.3.x for now, just update your copy of file vf_xpsnr.c manually.
> 
> Christian

Thank you for your reply！ After update to the newest code and rebuild on  FFmpeg 4.4, the result of 8bit is no problem now.

**Comment by crhelmrich** [comment] 2021-08-11 13:00
Great! The latest commit should also have fixed the 10-bit 720p input problem. Please confirm, then I'll close this issue.

Christian

**Comment by rtingo** [comment] 2021-08-12 02:25
> Great! The latest commit should also have fixed the 10-bit 720p input problem. Please confirm, then I'll close this issue.
> 
> Christian

OK, there is no problem with the input of  10-bit yuv420p! Thanks again！

**Comment by crhelmrich** [comment] 2021-08-12 09:06
Wonderful, closing this issue. Thanks again for reporting!

Christian

**Closed by crhelmrich** 2021-08-12 09:06 UTC
Labels: bug
